rm(list=ls(all=TRUE))
source("applyDiffusion.R")
source("biofilm.R")
source( "diffusion.R" )
source("extendBacteriaGrid.R")
source( "extendNutrientGrid.R")
source("initBacteriaGrid.R" )
source("initNutrientGrid.R")
source("applyDiffusionExtended.R")
source("consumption.R")
source("grow.R")
source("pickNeighbor.R")
source("showNutrientGraphs.R")
source("showBacteriaGraphs.R") 
#source("test.R")  
